version: '3.8'

services:

  mysql-db:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password     
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: p4ssw0rd
      MYSQL_DATABASE: db1
    ports:
      - "3306:3306"

  adminer:
    image: adminer:4
    container_name: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
